version: 2.1

jobs:
  build_intel:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Build and upload wheels
          command: |
            brew install python3.8 python3.9 python3.10 python3.11
            pyenv local 3.8
            python -m pip install -U pip
            python -m pip install wheel
                        
            arch_flags="-a intel -f"
            scripts/create_macos_arm_wheels ${arch_flags}
            
            for version in 3.8 3.9 3.10 3.11; do
              pyenv local "${version}"
              python -m pip install -U pip
              python -m pip install wheel
              
              arch_flags="-a intel"
              scripts/create_macos_arm_wheels ${arch_flags}
            done
            
            mkdir -p artifacts
            cp python/dist/fixed_wheel/*.whl artifacts/

      - store_artifacts:
          path: artifacts
          destination: wheels

workflows:
  build_and_upload_wheels:
    jobs:
      - build_intel
