version: 2.1

jobs:
  build_intel:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Build and upload wheels
          command: |
            brew install python@3.8 python@3.9 python@3.10 python@3.11

            git submodule update --init --recursive
            
            for version in 3.8 3.9 3.10 3.11; do
              python"${version}" -m venv env"${version}"
              source env"${version}"/bin/activate

              python -m pip install -U pip
              python -m pip install wheel
              
              if [[ "${version}" == "3.8" ]]; then
                arch_flags="-a intel -f"
              else
                arch_flags="-a intel"
              fi
              
              scripts/create_macos_arm_wheels.sh ${arch_flags}
              
              deactivate
            done
            
            mkdir -p artifacts
            cp python/dist/fixed_wheel/*.whl artifacts/

      - store_artifacts:
          path: artifacts
          destination: wheels

workflows:
  build_and_upload_wheels:
    jobs:
      - build_intel
